#!/usr/bin/python3

import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('--port', '-p', default=26622, type=int)
parser.add_argument('--user', '-u', default='jun', type=str)

args = parser.parse_args()
os.system('ssh -N -f -L 8888:127.0.0.1:8889 -p {} {}@202.120.32.244'.format(args.port, args.user))
